
version: 2

models:
  - name: cost_of_living
    columns:
      - name: city
        tests:
          - not_null
  - name: orders
    columns:
      - name: id
        tests:
          - not_null
          - unique
sources:
  - name: airbyte
    tables:
      - name: col
  - name: public
    tables:
      - name: dynamic_entity
